coverage:
  status:
    project:
      components:
        target: 100%
        threshold: 1%
        paths:
          - packages/react/src/components/
codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
