coverage:
  status:
    project:
      components:
        paths:
          - tests/components
          - packages/react/src/components*
        target: 100%
        threshold: 1%
  ignore:
    - 'packages/react/src/__tests__'
    - 'packages/react/src/internal'
    - 'packages/react/src/prop-types'
    - 'packages/react/src/tools'
    - 'packages/react/src/types'
    - 'packages/react/src/__tests__'
