coverage:
  status:
    project:
      components:
        target: 100%
        threshold: 1%
        paths:
          - packages/react/src/components/

  # ignore:
  #   - 'packages/react/src/__tests__'
  #   - 'packages/react/src/internal'
  #   - 'packages/react/src/prop-types'
  #   - 'packages/react/src/tools'
  #   - 'packages/react/src/types'
  #   - 'packages/react/src/__tests__'
