name: Jest components

  on:
  push:
    paths:
      - "packages/react/src/components/**"
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test JS frontend
    defaults:
      run:
        working-directory: ./packages/react/src/components
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: Install requirements
        run: npm install
      - name: Run tests and collect coverage
        run: npm run test
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v4.2.0
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          flags: jest-components